server:
  port: 5005
spring:
  application:
    name: notification
  zipkin:
    base-url: http://localhost:9411
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/notification
    password: 'postgres'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
      #ddl-auto: update
    show-sql: 'true'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    #enabled: false
