server:
  port: 5001
spring:
  application:
    name: customer
  zipkin:
    base-url: http://localhost:9411
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/customer
    password: 'postgres'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
      #ddl-auto: update
    show-sql: 'true'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    #enabled: false
rabbitmq:
  exchanges:
    internal: internal.exchange #topic exchange
  queues:
    notification: notification.queue #queue name
  routing-keys:
    internal-notification: internal.notification.routing-key  #routing key to bind topic with the queue
  # producer ----(all messages go to the Topic)---> topic exchange (will bind the route with the queue using routing key) -------> queue (queue name) -------> consumer


